project:
  type: website
  resources:
    - cv.pdf

website:
  title: "Pedro I. Rosas-Medina"
  description: "Análisis de Datos y Ciencia Política"
  site-url: https://prosasmed.github.io/mi-webpage/
  repo-url: https://github.com/Prosasmed/mi-webpage.git
  repo-actions: [issue]
  open-graph:
    locale: es_MX
  twitter-card:
    creator: "@Pedro0909"
  page-navigation: TRUE
  back-to-top-navigation: TRUE
  navbar:
    right:
      - href: index.qmd
        text: Inicio
      - text: "Investigación"
        href: research
      - text: "Conferencias"
        href: conferences
      - text: "Blog"
        href: blog.html
  page-footer:
    border: true
    left: |
      Powered by [{{< iconify simple-icons:quarto >}} Quarto](https://quarto.org).
    center: |
      Pedro I. Rosas-Medina
    right: |
      Repo [{{< iconify simple-icons:github >}} GitHub](https://github.com/Prosasmed/mi-webpage.git).
      

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    toc: false
    code-copy: TRUE
    code-link: TRUE
    anchor-sections: TRUE
    email-obfuscation: javascript
    link-external-newwindow: TRUE

lightbox: auto



