project:
  type: website
  resources:
    - cv.pdf

website:
  title: "Pedro I. Rosas-Medina"
  description: "Análisis de Datos y Ciencia Política"
  open-graph:
    locale: es_MX
  twitter-card:
    creator: "@Pedro0909"
  navbar:
    right:
      - href: index.qmd
        text: Inicio
      - text: "Investigación"
        href: research
  page-footer:
    left: "Pedro I. Rosas-Medina. Este sitio fue creado a través de Quarto Websites."

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    toc: false



