---
title: "Conferencias y presentaciones"
---

## Recientes

* **"Necesidades o lujos: inversión educativa de los hogares en México"**.
  + Conferencia presentada en el [Congreso Nacional de Ciencias Sociales: las Ciencias Sociales y los retos para la democracia mexicana](https://www.comecso.com/congreso-ix/programa-ixcongreso), el 8 de abril de 2024.
  + Presentación disponible [aquí](ixcncs_pirm.pdf).
* **"Democracia y educación en Latinoamérica"**.
  + Ponencia presentada en el [Congreso Latinoamericano de Estudiantes de Posgrados en Ciencias Sociales (CLEPSO)](https://clepso.flacso.edu.mx/programa), el 28 de agosto de 2024.
* **"La educación como un lujo en México"**.
  + Ponencia presentada en el [Congreso Latinoamericano de Estudiantes de Posgrados en Ciencias Sociales (CLEPSO)](https://clepso.flacso.edu.mx/programa), el 29 de agosto de 2024.

## Previo a 2024

* **"Desigualdad y preferencias hacia la educación: un estudio entre países de la OCDE"**.
  + Ponencia presentada en el [Seminario de Investigación del Doctorado en Ciencias Sociales, Flacso México](https://www.flacso.edu.mx/seminario-investigacion-estudiantes-dcs/), el 22 de septiembre de 2023.
  + Presentación disponible [aquí](seminario_pedroRosas.pdf).
  + _Working Paper_ disponible [aquí](seminario_pirm.pdf).
* **"Estabilidad mediante cambios en las políticas: inversión en la política de extensión a la jornada escolar en México"**.
  + Ponencia presentada en el [Congreso Latinoamericano de Estudiantes de Posgrados en Ciencias Sociales (CLEPSO)](https://clepso.flacso.edu.mx/programa), el 25 de agosto de 2022.
  + Presentación disponible [aquí](PedroRosas_CLEPSO2022.pdf).
* **"Políticas Públicas y Sustentabilidad"**.
  + Ponencia presentada en la [Jornada de Administración y Políticas Públicas](difusion.jpg), de la Universidad Autónoma de Morelos, el 3 de junio de 2021.
  + Presentación disponible [aquí](uaem_PedroRosas.pdf).
* **"La reforma político-administrativa a la PCM: agenda, problemas, e institucionalismo"**.
  + Ponencia presentada en el [Primer Coloquio de Estudiantes en Políticas Públicas](uam2019_programa.pdf), organizado por la Universidad Autónoma Metropolitana, el 25 de octubre de 2019.
  + Presentación disponible [aquí](uam2019_PIRM.pdf).