{
  "hash": "8676b5d264cdc490d48301a92a51919f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Efectos marginales condicionales\"\ndescription: \"Análisis de efectos fijos de dos vías, y construcción de gráficos de efectos marginales para estimaciones con covariantes en interacción.\"\nauthor:\n  - name: Pedro I. Rosas-Medina\n    url: {}\ndate: \"2025-01-20\"\ncategories: [R, Econometrics, tidyverse, ggplot2]\nimage: banner.png\nformat: \n  html:\n    toc: true\nengine: knitr\n---\n\n\n\n\n\nAntes de que todo lo tuviéramos en nuestros celulares, las fotos las imprimíamos, y las colocábamos en álbumes. ¿Alguna vez viste alguno? Muchas veces, estos _libros_ contaban con páginas y páginas de fotos familiares, donde generalmente aparecían las mismas personas en un mismo lugar: la casa de los abuelos, o el jardín donde la familia jugaba..\n\nImagina que estás viendo un álbum de fotos, donde el fondo de cada una de estas es siempre el mismo, pero las personas cambian: crecen, se mudan, cambian de peinado, o incluso de estilo. ¿Cómo podrías analizar estos cambios en tu familia, sin distraerte con el fondo o la decoración propia de la casa donde se tomó la foto? Una forma sería ignorar estos _elementos fijos_, enfocándote únicamente en las _diferencias de un año a otro_.\n\nPues bien, ¡eso es más o menos lo que hacen los modelos de efectos fijos! En lugar de intentar captar todo, estos modelos \"ignoran\" las cosas que no cambian con el tiempo (como el fondo en las fotos) y se centran en los cambios dentro de cada grupo o unidad (las personas en las fotos). Esto los convierte en una herramienta fantástica para responder preguntas como: _¿Qué pasa cuando una política cambia en un país?_ o _¿Cómo afecta un cambio de estrategia en una empresa a sus resultados?_\n\nEn esta publicación, no me interesa demasiado explicar la lógica detrás de un modelo de efectos fijos, o los tipos de estos. Joshua D. Angrist \\& Jörn-Steffen Pischke, por ejemplo, brindan una excelente explicación al respecto en su libro [Mostly Harmless Econometrics](https://www.mostlyharmlesseconometrics.com); mientras que Arne Henningsen \\& Géraldine Henningsen, en su capítulo [Analysis of Panel Data Using R](https://www.sciencedirect.com/science/article/abs/pii/B9780128143674000125), ofrecen una explicación detallada de este tipo de modelación a través de `R`.\n\nEn cambio, aquí explicaré un ejemplo que, personalmente, me causó demasiados problemas en mi tesis doctoral: la visualización de efectos marginales condicionales promedio, derivado de estmaciones de modelos de efectos fijos de dos vías.\n\n## El caso...\nEn mi tesis doctoral construí diferentes modelos de efectos fijos de dos vías con el objetivo de entender las razones por las cuales, en Latinoamérica, los países de la región expandieron los niveles de financiamiento público educativo a partir de la década de los 90; y priorizaron sistemáticamente el gasto entre niveles parte de los subsistemas de enseñanza básica, respecto a la educación superior, o profesional.\n\nEvidentemente, el caso es mucho más amplio, y en este _post_ no quisiera adentrar sobre el _por qué_ de cada covariante incluida en los modelos. Sin embargo, es preciso mencionar _por qué_ un modelo de efectos fijos.\n\n### Two-way Fixed Effects Models\nUno usa modelos de efectos fijos de dos vías cuando lo que intentas es controlar la heterogeneidad no observada que es constante en el tiempo para cada unidad transversal (en español: países, individuos, o incluso empresas), y simultáneamente por factores inobservables que son constantes a través de las unidades en un periodo específico (otra vez, en español: el tiempo).\n\n¿Pero cuándo es útil este análisis de datos tipo panel?\n\n1. Cuando **existen efectos específicos de las unidades**: cuando quieran capturar características inherentes a las unidades (como diferencias culturales, políticas, o estructurales entre países) que no varían en el tiempo.\n2. Cuando **existen efectos específicos del tiempo**: es decir, cuando quieran modelar influencias comunes a todas las unidades en un momento dado, como _shocks_ macroeconómicos globales, o eventos específicos de un periodo.\n3. Cuando **la variación dentro de las unidades y a través del tiempo es clave**: es decir, cuando el interés recaiga en identificar relaciones causales utilizando la variación interna de las unidades, descontando los efectos constantes de las unidades y del tiempo.\n\n### La base de datos\nLa base de datos que emplearemos en este ejemplo es de elaboración propia, y pueden encontrarla en mi [Github](https://github.com/Prosasmed/tesis_flacso.git). En términos generales, este marco de datos es de tipo panel, y cuenta con mucha información sobre educación, economía, contexto político y social de $18$ países latinoamericanos, entre $1970$ y $2018$. Sobre fuentes de información y demás, una vez más, los invito a que revisen el repositorio, pues ahí tienen todo lo necesario... Sin embargo, quedémonos con esta puntualización para el ejemplo que elaboraremos en este _post_:\n\n* **Variable dependiente**: gasto público educativo de cada gobierno latinoamericano incluido en la muestra, entre 1970 y 2018, como proporción del PIB.\n* **Variables independientes**:\n  + _Ideología gubernamental_: variable continua con puntajes de ideología gubernamental, entre una escala restringida entre $1$ y $20$, donde los extremos representan posiciones ideológicas extremas (izquierda y derecha, respectivamente).\n  + _Globalizacón_: nivel de globalización del país para el año observado. Promedio entre $0$ y $100$, donde los extremos representan el nivel de apertura a los mercados internacionales de bienes y servicios (sin globalización y completamente globalizado, respectivamente).\n* **Variables de control**: conjunto de variables de control que definen características sociales y económicas de los gobiernos latinoamericanos para el periodo observado.\n\n### Estimación\nLa estimación de un modelo de efectos fijos de dos vías en `R`, generalmente sigue la función `plm()`, de la paquetería `plm`. El modelo busca evaluar cómo varias variables explicativas impactan en la variable dependiente `exp_w1`, controlando por heterogeneidad no observada específica de las unidades (en este caso, países) y de los periodos (aquí: años).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nh1_tw2 <- plm(exp_w1 ~ VP_mean + KOFGIdj + VP_mean * KOFGIdj +\n                pop_w2 + pop_w1_ln + eco_w4 + eco_w6 + eco_w16,\n              data = h1,\n              model = \"within\",\n              effect = \"twoways\")\n```\n:::\n\n\n\nDesglosemos lo anterior:\n\n1. La función `plm()` estima modelos para datos tipo panel:\n  * La fórmula `exp_w1 ~ ...` nos dice que:\n    + `exp_w1` es la variable dependiente,\n    + `VP_mean` y `KOFGIdj` son las variables explicativas principales.\n    + `VP_mean * KOFGIdj` es el término de interacción para analizar si el efecto de la polarización política depende del nivel de globalización.\n    + `pop_w2`, `pop_w1_ln`, `eco_w4`, `eco_w6`, `eco_w16` son las variables de control relacionadas a población y economía de los países.\n  * `data = h1` es la base de datos que contiene las variables.\n  * `model = \"within\"` especifica un modelo de efectos fijos, que elimina la heterogeneidad no observada constante para cada unidad y cada periodo.\n  * `effect = \"twoways\"` indica un modelo de efectos fijos de dos vías, controlando por efectos específicos de las unidades y periodos.\n\nAhora podemos ver los resultados:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(h1_tw2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTwoways effects Within Model\n\nCall:\nplm(formula = exp_w1 ~ VP_mean + KOFGIdj + VP_mean * KOFGIdj + \n    pop_w2 + pop_w1_ln + eco_w4 + eco_w6 + eco_w16, data = h1, \n    effect = \"twoways\", model = \"within\")\n\nUnbalanced Panel: n = 17, T = 10-27, N = 342\n\nResiduals:\n     Min.   1st Qu.    Median   3rd Qu.      Max. \n-2.311338 -0.333117  0.037205  0.369118  2.590839 \n\nCoefficients:\n                   Estimate  Std. Error t-value  Pr(>|t|)    \nVP_mean          0.37518739  0.09064829  4.1389 4.639e-05 ***\nKOFGIdj          0.11489022  0.02568127  4.4737 1.125e-05 ***\npop_w2           0.11828132  0.05723363  2.0666   0.03970 *  \npop_w1_ln        0.07380443  1.10280716  0.0669   0.94669    \neco_w4          -0.00013629  0.00005570 -2.4468   0.01504 *  \neco_w6          -0.03721986  0.01604994 -2.3190   0.02113 *  \neco_w16          0.02632195  0.02207769  1.1922   0.23419    \nVP_mean:KOFGIdj -0.00569599  0.00135620 -4.2000 3.606e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nTotal Sum of Squares:    137.91\nResidual Sum of Squares: 123.21\nR-Squared:      0.10659\nAdj. R-Squared: -0.10381\nF-statistic: 4.1163 on 8 and 276 DF, p-value: 0.00011713\n```\n\n\n:::\n:::\n\n\n\nAntes de seguir, interpretemos rápidamente lo encontrado:\n\n- **`VP_mean` (polarización ideológica)**: Un aumento en la polarización incrementa significativamente el gasto educativo (coeficiente $= 0.375, p < 0.001$).\n- **`KOFGIdj` (globalización)**: La globalización también tiene un efecto positivo y significativo sobre el gasto educativo (coeficiente $= 0.115, p < 0.001$).\n- **Interacción `VP_mean:KOFGIdj`**: El coeficiente de $-0.0057 (p < 0.001)$ indica que el efecto positivo de la polarización disminuye a medida que aumenta el grado de globalización.\n- El **R-cuadrado** ($0.107$) indica que el modelo explica aproximadamente el $10.7\\%$ de la variación en el gasto educativo. Este nivel de ajuste es común en modelos de datos panel con efectos fijos, donde gran parte de la variación ya está controlada por efectos no observados.\n- Por tanto, la polarización ideológica y la globalización tienen efectos significativos sobre el gasto educativo público. Sin embargo, la interacción negativa entre ambas variables sugiere que la globalización modera el impacto de la polarización, disminuyendo su efecto positivo a medida que los niveles de globalización aumentan.\n\nCon el objetivo de garantizar que los errores estándar reportados sean **robustos a la heterocedasticidad**, a continuación, se calculan estos a través de la función `coeftest()`. Este paso es **fundamental** en el análisis de datos tipo panel, donde la varianza de los errores puede no ser constante entre observaciones, lo que podría sesgar las inferencias estadísticas si no se corrige.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoeftest(h1_tw2, vcov = vcovHC(h1_tw2, type = \"HC1\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n                   Estimate  Std. Error t value Pr(>|t|)  \nVP_mean          0.37518739  0.17180062  2.1839  0.02981 *\nKOFGIdj          0.11489022  0.04793220  2.3969  0.01720 *\npop_w2           0.11828132  0.11752730  1.0064  0.31510  \npop_w1_ln        0.07380443  3.17545949  0.0232  0.98147  \neco_w4          -0.00013629  0.00013802 -0.9874  0.32430  \neco_w6          -0.03721986  0.02317632 -1.6059  0.10943  \neco_w16          0.02632195  0.04029425  0.6532  0.51414  \nVP_mean:KOFGIdj -0.00569599  0.00272008 -2.0940  0.03717 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n### ¿Y ahora? Grafiquemos resultados\n¡Ya... casi! Ahora vamos con el propósito de este _post_: el análisis de efectos marginales condicionales para ilustrar la forma en que el efecto de la ideología `VP_mean`, varía sobre el gasto educativo `exp_w1`, según el nivel de globalización `KOFGIdj`. A continuación, desglosaré qué es este tipo de análisis visual, y cómo se construye en `R` a través del ejemplo en cuestión.\n\n## Efectos marginales condicionales\nEn ciencias sociales, y fundamentalmente, en ciencia política, la mayoría de argumentos teóricos postulan que el efecto de ciertas variables varía dependiendo del contexto social, político, económico, o estratégico... Por tanto, encontrar modelos econométricos como el de este ejemplo, donde se postula una interacción entre variables, es algo muy usual en la vida real. Pero, ¿qué quiero decir con esto?\n\nEl ejemplo de este _post_ aborda una hipótesis condicional que sigue una estructura estándar en la literatura sobre efectos marginales condicionales. Específicamente, se plantea que la **posición ideológica gubernamental** ($X$) tiene un efecto positivo sobre el **gasto público educativo** ($Y$), cuyo impacto se ve amplificado a medida que **la globalización** ($Z$) aumenta. Formalmente, la hipótesis puede expresarse como una interacción entre $X$ y $Z$, donde el efecto de $X$ sobre $Y$ depende del valor de $Z$:\n\n\\begin{equation}\nY_{it} = \\beta_0 + \\beta_1 X_{it} + \\beta_2 Z_t + \\beta_3 (X_{it} \\times Z_{it}) + \\alpha_i + \\lambda_t + \\epsilon_{it}\n\\end{equation}\n\nDonde:\n\n- **$Y_{it}$**: Gasto público educativo de país $i$ en el tiempo $t$.\n- **$X_{it}$**: Posición ideológica del gobierno del país $i$ en el tiempo $t$.\n- **$Z_{it}$**: Nivel de globalización en el tiempo $t$.\n- **$X_{it} \\times Z_{it}$**: Término de interacción entre la ideología del gobierno y la globalización.\n- **$\\alpha_i$**: Efectos fijos por unidad (por ejemplo, país).\n- **$\\lambda_t$**: Efectos fijos por tiempo (por ejemplo, año).\n- **$\\epsilon_{it}$**: Error aleatorio.\n\nPero, **¿qué es el efecto marginal condicional?** Este concepto refiere a la variación en la expectativa de la variable dependiente ante un cambio en una variable independiente, condicionado a un valor específico de otra variable, que puede estar involucrada en una interacción, o estar controlada por otros factores. El concepto, por tanto, permite entender cómo cambia la relación entre las variables frente a diferentes contextos, proporcionando una interpretación más precisa sobre las dinámicas subyacentes del modelo. ¿Y cómo lo obtenemos?\n\nPara el modelo en cuestión, el efecto marginal de $X_{it}$, está dado por\n\n\\begin{equation}\n\\frac{\\partial Y_{it}}{\\partial X_{it}} = \\beta_1 X_{it} + \\beta_3 Z.\n\\end{equation}\n\nPor tanto, a menos que el coeficiente asociado al producto ($\\beta_{3}$) sea igual a $0$, el efecto marginal de $X_{it}$ es condicional al valor de $Z_{it}$.\n\nEn resumen: la interacción entre las variables de ideología gubernamental y globalización implica que el efecto de la posición ideológica gubernamental sobre el gasto público educativo no es constante, sino que depende del punto de apertura comercial a los mercados internacionales de bienes y servicios en el que se encuentre cada gobierno en un periodo específico. En otras palabras, el impacto de la ideología sobre el gasto se intensifica o atenúa según el contexto global en el que se encuentre el país.\n\nEste tipo de interacción es crucial para obtener una comprensión más completa de las relaciones entre variables en contextos dinámicos. Así, el efecto marginal condicional nos permitirá observar cómo cambia el impacto de una variable en función de otra, proporcionando una perspectiva más detallada sobre cómo las variables actúan conjuntamente dentro de un marco empírico como el que estamos analizando en este ejemplo.\n\n### Gráficos de efectos marginales condicionales\nAntes de iniciar a construir el `ggplot` del gráfico de efectos marginales condicionales, lo primero que haremos es generar un vector de valores numéricos entre $0$ y $100$, con el objetivo de forzar el cálculo de los efectos marginales condicionales sobre todo el rango posible de valores que puede tener la variable condicionand ($Z$). \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkoffgi_values <- seq(from = 0, to = 100, by = 0.20)\n```\n:::\n\n\n\nCon base en esto, ahora calcularemos los efectos marginales condicionales promedio para los valores específicos de $Z$. Para ello, utilizaremos la función `avg_slopes()` de la paquetería `marginaleffects`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(marginaleffects)\nc_me_unobserved_avg <- marginaleffects::avg_slopes(\n  model = h1_tw2,\n  newdata = datagrid(KOFGIdj = koffgi_values),\n  variables = \"VP_mean\",\n  by = \"KOFGIdj\",\n  conf_level = 0.90\n)\n```\n:::\n\n\n\n¿Qué hicimos?\n\n* `model = h1_tw2` es el modelo previamente ajustado con la función `plm()`, en el que se estimaron los efectos fijos de dos vías para el gasto público educativo, la ideología y la globalización.\n* `newdata = datagrid(KOFGIdj = koffgi_values)`: Esta línea define un conjunto de datos simulado con diferentes valores de la variable `KOFGIdj` (nivel de globalización). Este nuevo conjunto de datos se utiliza para evaluar cómo cambia el efecto de `VP_mean` (ideología gubernamental) en función de los valores de `KOFGIdj`.\n* `variables = \"VP_mean\"`: Especifica que los efectos marginales deben calcularse para la variable `VP_mean`, que es la posición ideológica del gobierno.\n* `by = \"KOFGIdj\"`: Indica que los efectos marginales de `VP_mean` deben calcularse para cada nivel de `KOFGIdj` (globalización), es decir, el cálculo se realiza de forma condicionada a los valores de esta variable.\n* `conf_level = 0.90`: Establece el nivel de confianza para los intervalos de confianza calculados, en este caso, un intervalo de confianza del $90\\%$.\n\nAhora sí, veamos nuestro gráfico de efectos marginales condicionales promedio:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc_me_unobserved_avg %>%\n  ggplot(aes(x = KOFGIdj, y = estimate)) +\n  geom_hline(yintercept = 0.00,\n             linetype = \"dashed\",\n             colour = \"grey25\") +\n  geom_line(color = \"dodgerblue2\",\n            linewidth = 0.9) +\n  geom_ribbon(aes(ymin = conf.low, ymax = conf.high),\n              alpha = 0.2,\n              colour = \"black\",\n              linetype = \"dotdash\",\n              fill = \"darkgrey\",\n              linewidth = 0.5) +\n  ggtitle(\"Efectos marginales condicionales\",\n          subtitle = \"Ideología, Globalización y Gasto Público Educativo\") +\n  labs(x = \"Nivel de globalización\",\n       y = \"Efecto de la ideología\",\n       caption = \"Fuente: elaboración propia con datos del Banco Mundial\") +\n  theme_apa(x.font.size = 10,\n            y.font.size = 10) +\n  theme(plot.title = element_text(size = 10),\n        axis.text.x = element_text(color = \"black\",\n                                   size = 8),\n        axis.text.y = element_text(color = \"black\",\n                                   size = 8),\n        plot.caption = element_text(hjust = 0))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/marginal-plot3-1.png){width=672}\n:::\n:::\n\n\n\nPero, ¿qué con esto? El gráfico nos dice mucho, pero vamos por partes.\n\nEn general, **el gráfico devela una pendiente negativa debido al coeficiente** $\\beta_{3}$ encontrado bajo la condición de interacción. De esto se deduce que:\n\n1. Cuando los países de la región se encuentran bajo condiciones económicas de completo cierre a los mercados internacionales de bienes y servicios, el efecto marginal de un movimiento ideológico gubernamental en una unidad hacia la derecha (más conservadores), se asociaría con un incremento significativo de $0.38$ puntos porcentuales sobre el financiamiento público del sector.\n\nSin embargo, esto no es todo. ¿Qué más podemos inferir?\n\n2. Cuanto más globalizado se encuentra un país, la relación observada tendería a decrecer en magnitud. Es decir: una vez que los países se globalizan por encima del $65.86\\%$, la promoción de políticas con un impacto superior sobre el fenómeno resultaría en retracciones bajo gobiernos ideológicamente de derecha, y el gasto educativo público total, o agregado.\n\nSi... ¿pero qué hay de la línea punteada horizontal en $0$?\n\nEl punto anterior nos da una pista. Hay un punto, específicamente en $65.86\\%$ de globalización, donde el efecto marginal de $X_{it}$ (ideología) sobre $Y_{it}$ (gasto educativo) es neutro... por eso la línea punteada horizontal en $0$: pues es aquí donde el efecto, valga la redundancia, es **nulo**. ¿Y cómo se obtiene? Recordemos: el efecto marginal condicional ($ME$) de $X_{it}$ sobre $Y_{it}$ dado $Z_{it}$ está dado por:\n\n\\begin{equation}\nME(X_{it} \\mid Z_{it}) = \\frac{\\partial Y_{it}}{\\partial X_{it}} = \\beta_1 X_{it} + \\beta_3 Z.\n\\end{equation}\n\nPor tanto, el punto donde $ME(X_{it} \\mid Z_{it}) = 0$, se encuentra resolviendo la derivada parcial de $X_{it}$ dado $Z_{it}$, es decir:\n\n\\begin{equation}\n\\beta_1 X_{it} + \\beta_3 Z_{it} = 0\n\\end{equation}\n\nEntonces, tenemos que para $Z_{it}$\n\n\\begin{align}\nZ_{it} &= -\\frac{\\beta_{1} X_{it}}{\\beta_{3} Z_{it}},\\\\\n-\\frac{0.37518739}{-0.00569599} = 65.86\n\\end{align}\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}